env:
   global:
     - NDK_VERSION=r9d

language: c

sudo: true

jdk: oraclejdk8

before_install:
    - wget http://dl.google.com/android/ndk/android-ndk-$NDK_VERSION-linux-x86_64.tar.bz2
    #- chmod +x android-ndk-$NDK_VERSION-linux-x86_64.bin
    #- ./android-ndk-$NDK_VERSION-linux-x86_64.bin | egrep -v ^Extracting
    - tar --bzip2 -xf android-ndk-$NDK_VERSION-linux-x86_64.tar.bz2
    - export ANDROID_NDK_HOME=`pwd`/android-ndk-$NDK_VERSION
    - export PATH=${PATH}:${ANDROID_NDK_HOME}   
    - echo ${PATH}
    - echo `pwd` 

script:
    - cd DataApi2/jni
    - ndk-build
    - cat /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.3.0/lib/octokit/client/authorizations.rb
   # - cat /home/travis/build.sh
   # - android list targets
   # - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
   # - emulator -avd test -no-skin -no-audio -no-window &
 
deploy:
   provider: releases
   user: "panhuidan"
   password: "$PAS"
   #api_key: 
   #  secure: fcea86f297f06d8d1008d930e43f85ae2590be2e
   file: DataApi2/libs/armeabi-v7a/libEditor.so DataApi2/libs/armeabi-v7a/libcurl.so
   skin_cleanup: true
  # on:
  #    tags: true
  #    all_branches: true


