env:
   global:
     - NDK_VERSION=r9d

language: android

sudo: false

jdk: oraclejdk8

android:
  components:
    - build-tools-19.1.0
    - android-19
    - sys-img-armeabi-v7a-android-19
    - extra-android-m2repository

before_install:
    - wget http://dl.google.com/android/ndk/android-ndk-$NDK_VERSION-linux-x86_64.tar.bz2
    - tar --bzip2 -xf android-ndk-$NDK_VERSION-linux-x86_64.tar.bz2
    - export ANDROID_NDK_HOME=`pwd`/android-ndk-$NDK_VERSION
    - export PATH=${PATH}:${ANDROID_NDK_HOME}   
    - echo ${PATH}
    - echo `pwd` 

script:
    - cd DataApi
    - ./gradlew build --info
    - cat /home/travis/build.sh
    - android list targets
    - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window &
