env:
   global:
     - NDK_VERSION=r9d

language: c

sudo: false

jdk: oraclejdk8

before_install:
    - wget http://dl.google.com/android/ndk/android-ndk-$NDK_VERSION-linux-x86_64.tar.bz2
    #- chmod +x android-ndk-$NDK_VERSION-linux-x86_64.bin
    #- ./android-ndk-$NDK_VERSION-linux-x86_64.bin | egrep -v ^Extracting
    - tar --bzip2 -xf android-ndk-$NDK_VERSION-linux-x86_64.tar.bz2
    - export ANDROID_NDK_HOME=`pwd`/android-ndk-$NDK_VERSION
    - export PATH=${PATH}:${ANDROID_NDK_HOME}   
    - echo ${PATH}
    - echo `pwd` 

script:
    - cd DataApi2/jni
    - ndk-build
   # - cat /home/travis/build.sh
   # - android list targets
   # - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
   # - emulator -avd test -no-skin -no-audio -no-window &
 
deploy:
   provider:releases
   api_key: 
     secure: b73b730508d1a81a25af30ad9563573575c82fd1
   file: DataApi2/libs/armeabi-v7a/libEditor.so DataApi2/libs/armeabi-v7a/libcurl.so
   skin_cleanup: true
   on:
      tags: true
      all_branches: true


