env:
   global:
     - NDK_VERSION=r9d

language: android

sudo: false

android:
  components:
    - build-tools-19.1.0
    - android-19
    - sys-img-armeabi-v7a-android-19

before_install:
    - wget http://dl.google.com/android/ndk/android-ndk-$NDK_VERSION-linux-x86_64.bin

script:
    - cd DataApi
    - TERM=dumb ./gradlew :app:assembleDebug
    - android list targets
    - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window &
