/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fastmap_dataapi_DataNativeApi */

#ifndef _Included_com_fastmap_dataapi_DataNativeApi
#define _Included_com_fastmap_dataapi_DataNativeApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    SnapPoint
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_fastmap_dataapi_DataNativeApi_SnapPoint
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    SnapLine
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fastmap_dataapi_DataNativeApi_SnapLine
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    SelectPois
 * Signature: (Ljava/lang/String;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_fastmap_dataapi_DataNativeApi_SelectPois
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    GetTotalPoiByFid
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fastmap_dataapi_DataNativeApi_GetTotalPoiByFid
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    InstallLayers
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fastmap_dataapi_DataNativeApi_InstallLayers
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    InstallJsonData
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fastmap_dataapi_DataNativeApi_InstallJsonData
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    DownloadFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/util/ArrayList;ILcom/fastmap/dataapi/Progress;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fastmap_dataapi_DataNativeApi_DownloadFile
  (JNIEnv *, jclass, jstring, jstring, jobject, jint, jobject, jint);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    CancelDownload
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_fastmap_dataapi_DataNativeApi_CancelDownload
  (JNIEnv *, jclass);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    UploadFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/util/ArrayList;ILcom/fastmap/dataapi/Progress;ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fastmap_dataapi_DataNativeApi_UploadFile
  (JNIEnv *, jclass, jstring, jstring, jobject, jint, jobject, jint, jstring);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    CancelUpload
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_fastmap_dataapi_DataNativeApi_CancelUpload
  (JNIEnv *, jclass);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    InsertPoi
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fastmap_dataapi_DataNativeApi_InsertPoi
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    UpdatePoi
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fastmap_dataapi_DataNativeApi_UpdatePoi
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    DeletePoi
 * Signature: (ILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fastmap_dataapi_DataNativeApi_DeletePoi
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    SetRootPath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_fastmap_dataapi_DataNativeApi_SetRootPath
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    SetUserId
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_fastmap_dataapi_DataNativeApi_SetUserId
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    GetDataPath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fastmap_dataapi_DataNativeApi_GetDataPath
  (JNIEnv *, jclass);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    SelectTips
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_fastmap_dataapi_DataNativeApi_SelectTips
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    InsertTips
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fastmap_dataapi_DataNativeApi_InsertTips
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    UpdateTips
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fastmap_dataapi_DataNativeApi_UpdateTips
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    SelectMetaData
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_fastmap_dataapi_DataNativeApi_SelectMetaData
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    GetPoiPhotoPath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fastmap_dataapi_DataNativeApi_GetPoiPhotoPath
  (JNIEnv *, jclass);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    GetTipsPhotoPath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fastmap_dataapi_DataNativeApi_GetTipsPhotoPath
  (JNIEnv *, jclass);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    GetRdLineByPid
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fastmap_dataapi_DataNativeApi_GetRdLineByPid
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    GetCountByCondition
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_fastmap_dataapi_DataNativeApi_GetCountByCondition
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    GetProjectCountByCondition
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_fastmap_dataapi_DataNativeApi_GetProjectCountByCondition
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    GetSignalLayerByCondition
 * Signature: (Ljava/lang/String;III)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_fastmap_dataapi_DataNativeApi_GetSignalLayerByCondition
  (JNIEnv *, jclass, jstring, jint, jint, jint);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    InitVerstionInfo
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fastmap_dataapi_DataNativeApi_InitVerstionInfo
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    DeleteTips
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fastmap_dataapi_DataNativeApi_DeleteTips
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    UpdateGridStatus
 * Signature: (Ljava/util/ArrayList;)I
 */
JNIEXPORT jint JNICALL Java_com_fastmap_dataapi_DataNativeApi_UpdateGridStatus
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    UpdateGridStatusByBox
 * Signature: (DDDD)I
 */
JNIEXPORT jint JNICALL Java_com_fastmap_dataapi_DataNativeApi_UpdateGridStatusByBox
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    InsertGpsLine
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fastmap_dataapi_DataNativeApi_InsertGpsLine
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    GetProjectInfo
 * Signature: (Ljava/lang/String;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_fastmap_dataapi_DataNativeApi_GetProjectInfo
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    GetProjectDetail
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_fastmap_dataapi_DataNativeApi_GetProjectDetail
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    GetTaskDetail
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_fastmap_dataapi_DataNativeApi_GetTaskDetail
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    GivenPathSnap
 * Signature: (Ljava/lang/String;Ljava/lang/String;D)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fastmap_dataapi_DataNativeApi_GivenPathSnap
  (JNIEnv *, jclass, jstring, jstring, jdouble);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    GetTipsRowkey
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fastmap_dataapi_DataNativeApi_GetTipsRowkey
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    GetCoremapModelVersion
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fastmap_dataapi_DataNativeApi_GetCoremapModelVersion
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    SnapRdNode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fastmap_dataapi_DataNativeApi_SnapRdNode
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    GetTipsByRowkey
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fastmap_dataapi_DataNativeApi_GetTipsByRowkey
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    InstallGdb
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lcom/fastmap/dataapi/Progress;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fastmap_dataapi_DataNativeApi_InstallGdb
  (JNIEnv *, jclass, jstring, jstring, jobject);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    CaclAngle
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)D
 */
JNIEXPORT jdouble JNICALL Java_com_fastmap_dataapi_DataNativeApi_CaclAngle
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    LocationMacth
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fastmap_dataapi_DataNativeApi_LocationMacth
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    PolygonSelectLines
 * Signature: (Ljava/lang/String;Z)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_fastmap_dataapi_DataNativeApi_PolygonSelectLines
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    RepalceGDB
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_fastmap_dataapi_DataNativeApi_RepalceGDB
  (JNIEnv *, jclass);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    UpdatePois
 * Signature: (Ljava/util/ArrayList;Ljava/lang/String;Ljava/lang/String;Ljava/util/ArrayList;Lcom/fastmap/dataapi/Progress;)I
 */
JNIEXPORT jint JNICALL Java_com_fastmap_dataapi_DataNativeApi_UpdatePois
  (JNIEnv *, jclass, jobject, jstring, jstring, jobject, jobject);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    GetDownloadOrUploadStatus
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fastmap_dataapi_DataNativeApi_GetDownloadOrUploadStatus
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    InsertInfos
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fastmap_dataapi_DataNativeApi_InsertInfos
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    UpdateInfo
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fastmap_dataapi_DataNativeApi_UpdateInfo
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    GetEditHistroyByFid
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fastmap_dataapi_DataNativeApi_GetEditHistroyByFid
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    QueryFeatures
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_fastmap_dataapi_DataNativeApi_QueryFeatures
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    GetDownloadPrepared
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fastmap_dataapi_DataNativeApi_GetDownloadPrepared
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    DownloadFile_2
 * Signature: (Ljava/lang/String;Lcom/fastmap/dataapi/Progress;)V
 */
JNIEXPORT void JNICALL Java_com_fastmap_dataapi_DataNativeApi_DownloadFile_12
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    GetUploadPrepared
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fastmap_dataapi_DataNativeApi_GetUploadPrepared
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    UploadFile_2
 * Signature: (Ljava/lang/String;Lcom/fastmap/dataapi/Progress;)V
 */
JNIEXPORT void JNICALL Java_com_fastmap_dataapi_DataNativeApi_UploadFile_12
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    QueryFeaturesBySql
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_fastmap_dataapi_DataNativeApi_QueryFeaturesBySql
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    RobTask
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fastmap_dataapi_DataNativeApi_RobTask
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    QueryTableByCondition
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ZZII)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_fastmap_dataapi_DataNativeApi_QueryTableByCondition
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jboolean, jboolean, jint, jint);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    InsertTrackPoint
 * Signature: (Lcom/fastmap/dataapi/data/TrackCollection;)I
 */
JNIEXPORT jint JNICALL Java_com_fastmap_dataapi_DataNativeApi_InsertTrackPoint
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    PoiStatistics
 * Signature: (Ljava/lang/String;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_fastmap_dataapi_DataNativeApi_PoiStatistics
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    InsertFeature
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fastmap_dataapi_DataNativeApi_InsertFeature
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    UpdateFeature
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fastmap_dataapi_DataNativeApi_UpdateFeature
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    DeleteFeature
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_fastmap_dataapi_DataNativeApi_DeleteFeature
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    GetCountByWhere
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fastmap_dataapi_DataNativeApi_GetCountByWhere
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    TrackStatistics
 * Signature: (Ljava/lang/String;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_fastmap_dataapi_DataNativeApi_TrackStatistics
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    DeleteTrack
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fastmap_dataapi_DataNativeApi_DeleteTrack
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    DeletePoiAndInfoByRegion
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fastmap_dataapi_DataNativeApi_DeletePoiAndInfoByRegion
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_fastmap_dataapi_DataNativeApi
 * Method:    Test
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fastmap_dataapi_DataNativeApi_Test
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
